# Backend/Dockerfile

FROM python:3.10-slim

WORKDIR /app

# Copy only what you need
COPY . .

# Install requirements
RUN pip install --no-cache-dir -r requirements.txt

# Set env for FastAPI
ENV PYTHONPATH=/app

# Run FastAPI app on port 8080
CMD ["uvicorn", "serve:app", "--host", "0.0.0.0", "--port", "8080"]
