name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build Docker and Push to GCR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker --quiet

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/react-frontend:${{ github.sha }} -f ./frontend/Dockerfile ./frontend

    - name: Push Docker image to GCR
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/react-frontend:${{ github.sha }}
